name = "hello-cosmo-go"
language = "tinygo"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpserver", "wasmcloud:keyvalue", "wasmcloud:builtin:logging"]
wasm_target = "wasm32-wasi-preview2"
wasi_preview2_adapter_path = "wasi_snapshot_preview1.v13-0-0.wasm"
wit_world = "hello-cosmo"
