name = "hello-cosmo-rust"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["wasmcloud:httpserver", "wasmcloud:keyvalue", "wasmcloud:builtin:logging"]
wasm_target = "wasm32-wasi-preview2"
